### ISSUE TITLE
An empty option in Secret Store dropdown list

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/data-transfer-hub#43]
When click on the **Credentials Store** dropdown list. It displays an empty option. 

![Screen Shot 2021-08-17 at 7 51 01 AM](https://user-images.githubusercontent.com/2173635/129643019-5ae901f2-93f7-4b10-a19c-b03292263fbd.png)

**Comment by bassemwanis** [comment]
@JoeShi, closing this issue, as mentioned in the comment above, this behavior is intentional to enable customers to select an empty credential when transferring public datasets.
